### ISSUE TITLE
US57 Bug 1

### ISSUE THREAD

**Issue by LaughingBarista** [ser316asu-2018/Hohenzollern#19] opened 2018-04-13 01:17 UTC
When running US57 through either gradle or eclipse and clicking the locations tab, adding a single location and then clicking the edit button causes the GUI to freeze up. Subsequent entries into the program render the Locations button unusable.

**Comment by tedwoelke** [comment] 2018-04-13 02:24
Was able to duplicate original issue and confirmed updates addressed and fixed bug

**Comment by btjansen** [comment] 2018-04-13 03:44
I was able to duplicate the issue upon discovery. The issue is now resolved in branch US57.

**Closed** 2018-04-13 03:46 UTC
Labels: Code Review
